# Generated by Django 2.2.5 on 2019-10-10 05:41

from django.db import migrations, models
import enactuswebApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('enactuswebApp', '0004_auto_20191005_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=enactuswebApp.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
            ],
        ),
    ]
